open_graph:
  enable: true
  twitter_id: # for open_graph meta

######## Sidebar ########
# 左上角显示的 logo 区域，包含图标、大标题、副标题
logo:
  avatar: '[{config.avatar}](/about/)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
  title: '[{config.title}](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  subtitle: Determination. | Everything is going to be okay.

menubar:
  columns: 3 # 一行多少个
  items: # 可按照自己需求增加，符合以下格式即可
    # id: 页面中高亮的 menu_id 
    # theme: 高亮时的颜色，仅 svg 中 fill="currentColor" 时有效
    # icon: 支持 svg/img 标签，可以定义在 icons.yml 文件中，也支持外部图片的 URL
    # title: 标题
    # url: 点击跳转到哪，支持相对路径和绝对路径
    - id: post
      theme: '#1BCDFC'
      icon: solar:planet-bold-duotone
      title: 博客
      url: /
    - id: about
      theme: '#3DC550'
      icon: solar:documents-bold-duotone
      title: 关于
      url: /about/
    - id: notebooks
      theme: '#FA6400'
      icon: solar:notebook-bookmark-bold-duotone
      title: 笔记
      url: /notebooks/
    # - id: friends
    #   theme: '#F44336'
    #   icon: solar:chat-square-like-bold-duotone
    #   title: 友链
    #   url: /friends/

######## Article ########
article:
  # 文章类型，决定布局风格，可以在 front-matter/topic/wiki 中覆盖此参数
  type: tech # tech: 默认技术类文章, story: 图文类文章，文字和段落间增距大
  # 缩进两个文字宽度，适合文字类博客，可以在 front-matter/topic/wiki 中覆盖此参数
  indent: # true / false
  # 封面图宽高比
  cover_ratio: 2
  # 文章内横幅宽高比
  banner_ratio: 2.5
  # 如果没有指定横幅，是否根据 tags 作为关键词搜索横幅图片？
  auto_banner: false # search from https://source.unsplash.com/
  # 如果没有指定 excerpt 和 description，将自动取多长的内容作为文章摘要？
  auto_excerpt: 128
  # 分类颜色
  category_color:
    '探索号': '#f44336'
  # 文章许可协议
  license: '本文采用 [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/deed.zh-hans) 许可协议，转载请注明出处。'
  # 分享
  share: [wechat, link]
  # 相关文章，需要安装插件 (for layout: post)
  # npm i hexo-related-popular-posts
  related_posts:
    enable: false
    max_count: 5


style:
  prefers_theme: auto # auto / light / dark
  smooth_scroll: true # true / false 开启时如果目录过长可能无法准确定位
  font-size:
    root: 16px # 改这个会影响全局所有文字的字号
    body: 17px # 影响正文区域的字号，如果改成 px 则不受 root 影响
    code: 85% # 相较于其所在行的文本大小，建议用百分比
    codeblock: 0.8125rem # 13px
  font-family:
    body: 'system-ui, "Microsoft Yahei", "Segoe UI", Arial, sans-serif'
    code: 'Menlo, Monaco, Consolas, system-ui, monospace, sans-serif'
    codeblock: 'Menlo, Monaco, Consolas, system-ui, monospace, sans-serif'
  text-align: left
  prefix:
    h2: https://api.iconify.design/ci:heading-h2.svg
  border-radius:
    card-l: 24px # 侧边栏、文章横幅位置的圆角
    card: 16px # 文章内大部分卡片的圆角
    card-s: 12px # 文章内小型卡片的圆角
    bar: 8px # 横条类元素的圆角
    image-l: 24px # 非技术类文章插图圆角
    image: 16px # 技术类文章插图圆角
    image-s: 8px # 评论区图片圆角（部分评论支持）
  color:
    # 主题色配置（不会根据明暗动态调整，请设置为通用的颜色）
    theme: 'hsl(192 98% 55%)' # 主题色
    accent: 'hsl(14 100% 57%)' # 强调色
    link: 'hsl(207 90% 54%)' # 超链接颜色
  animated_avatar:
    animate: auto # auto, always
    background: https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/avatar/round/rainbow64@3x.webp
  codeblock:
    scrollbar: 4px
    highlightjs_theme: https://gcore.jsdelivr.net/gh/highlightjs/cdn-release@11.9/build/styles/atom-one-dark.min.css
  loading:
    loading: 正在加载
    error: 加载失败，请稍后重试。
  gradient: # https://webgradients.com/
    start: 'linear-gradient(to right, hsl(215, 95%, 64%), hsl(195, 95%, 60%), hsl(165, 95%, 56%), hsl(165, 95%, 56%), hsl(195 95% 60%), hsl(215, 95%, 64%))'
  leftbar:
    # 可以设置：纯色/渐变色/图片作为背景
    background-color: var(--card) # var(--block)
    background-image: url(https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.13/image/sidebar-bg1@small.jpg)
    blur-px: 100px
    blur-bg: var(--bg-a60)
    background-opacity: 0.8
  paginator:
    prev: https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/arrow/f049bbd4e88ec.svg
    next: https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/arrow/064b95430caf4.svg
  error_page: https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/404/1c830bfcd517d.svg
  site: # 使用 background-image 后，blur 设置才有效
    background-image: url(https://cdn.jsdmirror.com/gh/omo-ri/omo-ri.github.io/source/assets/images/bg.jpg)
    blur-px: 6px
    blur-bg: var(--bg-a50)
    blur-sat: 150%
  # 技术文章内页各级标题前面的符号
  header_prefix:
    h2: '#'
    h3: '='
    h4: '|'
    h5: ':'
